Traceback (most recent call last):
  File "/Users/kmilo/miniconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/kmilo/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kmilo/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/kmilo/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/kmilo/miniconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/kmilo/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/kmilo/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/kmilo/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# ahora con vals diferentes

# angulo
t = np.linspace(0, 2.*np.pi, 100) # s
th = 0
th = w * t + th_0 # rad

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/zz/qrq62qr91b50sgmzsqb1jx2w0000gn/T/ipykernel_71244/2283629724.py[0m in [0;36m<module>[0;34m[0m
[1;32m      4[0m [0mt[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mlinspace[0m[0;34m([0m[0;36m0[0m[0;34m,[0m [0;36m2.[0m[0;34m*[0m[0mnp[0m[0;34m.[0m[0mpi[0m[0;34m,[0m [0;36m100[0m[0;34m)[0m [0;31m# s[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mth[0m [0;34m=[0m [0;36m0[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 6[0;31m [0mth[0m [0;34m=[0m [0mw[0m [0;34m*[0m [0mt[0m [0;34m+[0m [0mth_0[0m [0;31m# rad[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'th_0' is not defined
NameError: name 'th_0' is not defined

